### ISSUE TITLE
User Settings Utility: select users based on FXB query

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MsCrmTools.UserSettingsUtility#1]
@rappen commented on [Wed Mar 15 2017](https://github.com/MscrmTools/XrmToolBox/issues/602)

Filter uses by using FXB to compose the query.

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/602#issuecomment-287695455)

Can you remind me if there is any doc on how to implement the appropriate interface?

---

@rappen commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/602#issuecomment-287699278)

Easiest to follow highlighted lines here: https://github.com/andypopkin/XrmToolBox---Bulk-Workflow-Execution/issues/4
There is also a blog post that describes it a bit more, but uses a custom class for the communication, which is not necessary: http://jonasrapp.innofactor.se/2015/04/IntegrateFXB.html

**Comment by rajyraman** [comment]
I have completed this. Need to do some more checking and refactoring before submitting PR. Has this been implemented already?

**Comment by MscrmTools** [comment]
No, I did not have time to do it so PR would be greatly appreciated!
