### ISSUE TITLE
New Format Setting

### ISSUE THREAD

**Issue by simes1** [MscrmTools/MsCrmTools.UserSettingsUtility#14]
Thank you for the latest improvement to the UserSettingUtility this is a very welcome addition.

Just one (very minor) wrinkle I've noticed so far - the number format doesn't appear to be displayed correctly in UserSettingsUtility for English (UK) [although it DOES appear to get set correctly - so looks like this is purely cosmetic?]
![crm user format settings](https://user-images.githubusercontent.com/11423243/28158304-390f4dcc-67b1-11e7-801e-6164b1de5edc.PNG)
![xrmtoolbox user settings utility format settings](https://user-images.githubusercontent.com/11423243/28158305-391299e6-67b1-11e7-859e-eb971b199e55.PNG)

--
Simon

**Comment by MscrmTools** [comment]
you are correct! fix is on its way
