### ISSUE TITLE
An error occured: 'SystemForm' entity doesn't contain attribute with Name = 'uniquename'

### ISSUE THREAD

**Issue by Lafil** [MscrmTools/MsCrmTools.UserSettingsUtility#15]
I am getting this error right after I load my users from my CRM 2013 On-Premises organization.
If I click Ok on the error and try to keep working by selecting a user, I get the error below and it closes out XrmToolBox. I am on latest version of both XrmToolBox and this plugin.

************** Texte de l'exception **************
System.InvalidOperationException: La séquence ne contient aucun élément correspondant.
   à System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   à MsCrmTools.UserSettingsUtility.MainControl.LoadCurrentUserSetting(Entity settings)
   à System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   à System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   à System.Windows.Forms.ListView.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by classmethods** [comment]
I concur with this:  User Settings Utility v. 1.2017.7.5: Select Loader User Settings retrieved this error.  Subsequently received when selecting a user:
************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MsCrmTools.UserSettingsUtility.MainControl.LoadCurrentUserSetting(Entity settings)
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by dodgster02** [comment]
The problem is due to the FetchXML statement that is being executed in the RetrieveDashboards method in the UserSettingsHelper class

`<fetch>
              <entity name='systemform' >
                <attribute name='formid' />
                <attribute name='name' />
                <filter>
                  <condition attribute='uniquename' operator='null' />
                  <condition attribute='objecttypecode' operator='eq' value='0' />
                </filter>
                <order attribute='name' />
              </entity>
            </fetch>`

In CRM 2015 the attribute "uniquename" does not exist, hence the fetch will fall over. It looks like this field is new from CRM 2016 onwards.

**Comment by rajyraman** [comment]
According to metadata, this attribute was introduced in 7.1.0.0. Are you on 7.0? I don't think this attribute is even used by the code, and so can be removed.

**Comment by dodgster02** [comment]
For CRM 2015 on premise we're currently on v0.2 so still within 7.0

**Comment by rajyraman** [comment]
Submitted PR.
