### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by norriqkve** [MscrmTools/MsCrmTools.UserSettingsUtility#2]
When selecting certain users, single or multiple, and then clicking Update Users(s) Settings.

![image](https://cloud.githubusercontent.com/assets/26870014/24605654/f80f583a-1869-11e7-9347-08073c3f6646.png)

**Comment by MscrmTools** [comment]
This is barely possible that it happens since the First method is used when retrieving a user with his id... Did you change the connection between loading users and updating users?
Anyway, I will add a check after retrieving the user
