### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by steveroh29** [MscrmTools/MsCrmTools.UserSettingsUtility#22]
Hi all, 
using your tool with Dynamics 365 online, XrmToolBox V.1.2018.1.20, I get this error when I click on the button "Update user Settings".
![image](https://user-images.githubusercontent.com/36946400/36828996-567052c2-1d1d-11e8-879f-6fcb85083f28.png)

Any idea ?
thanks & regards, 
Steve

**Comment by MscrmTools** [comment]
Could you precise what settings you tried to update? That might help to find source of the error

**Comment by steveroh29** [comment]
Hi, I've tried to update several settings, for one or several users. For example the user format, or the number of items per view. Differents tries but always the same error.

Thanks 
Steve

**Comment by MscrmTools** [comment]
@steveroh29 do you still experience the issue with latest version? trying to cleanup issues...

**Comment by steveroh29** [comment]
Resolved with last version
