### ISSUE TITLE
User Settings Utility:  Able to pull down user settings, but unable to push up other than my own (System Admin role in use)

### ISSUE THREAD

**Issue by DigitalFrog007** [MscrmTools/MsCrmTools.UserSettingsUtility#29]
Was working fine for me a few months ago, very useful tool.  Went to use this week and I can pull down all the user settings, but get an error when pushing changes back up for any but my own.
![image](https://user-images.githubusercontent.com/47428314/52431151-e5de0480-2ac4-11e9-9f61-dce599b06b4d.png)

Cleared the logs and did a test, this was the only entry in the new log:
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/6/2019 1:15:51 PM  OrganizationWebProxyClient is null

Not sure if this is a configuration issue, or a change by MS to the APIs?

**Comment by MscrmTools** [comment]
Does it still occurs?

**Comment by objecto** [comment]
By trial and error found that to be able to massively change user settings, the users should have the below Create, Read, Update rights.
![image](https://user-images.githubusercontent.com/35916868/59099093-dfed1880-892a-11e9-85a5-d6ff8ae27131.png)

**Comment by MscrmTools** [comment]
Thanks for the info
