### ISSUE TITLE
Error when updating users after logging in with SDK control

### ISSUE THREAD

**Issue by bennyboy23** [MscrmTools/MsCrmTools.UserSettingsUtility#33]
Hi,
When I use this utility on a connection made with the new SDK control, I am giving a connection error.
I can retrieve the users however I cannot update them without an error.

**Comment by MscrmTools** [comment]
I will review this specific scenario but that is possible that it is not possible to use this plugin when using the SDK login control

**Comment by MscrmTools** [comment]
Could you try again this scenario with the latest version published (1.2019.10.10)?

**Comment by MscrmTools** [comment]
@bennyboy23 Any news on this one?
I'm closing the issue. 
Will reopen if this is still an issue
