### ISSUE TITLE
Won't remove from Plugin Store after install

### ISSUE THREAD

**Issue by JamesStuder** [MscrmTools/MsCrmTools.UserSettingsUtility#34]
Since the last update this plugin is stuck in the plugin store, even after install.  Both the latest version and installed version so the same.  Says that there is a pending update, but every time I try to "update" it, nothing happens.  I am running the latest stable release of XrmToolBox and have the latest plugins installed.

**Comment by mscottsewell** [comment]
I'm experiencing the same.

**Comment by MscrmTools** [comment]
I will review this.
Sorry for the inconvenience

**Comment by MscrmTools** [comment]
What versions (installed and available) are displayed in Plugins Store?

**Comment by JamesStuder** [comment]
Latest Version = 1.2019.8.28 and Installed Version = 1.2019.3.19

**Comment by JamesStuder** [comment]
Sorry ignore the versions above.  I got them mixed up with a different plugin.  This issue is the same as #35

**Comment by MscrmTools** [comment]
Will be fixed in next release of XrmToolBox.
