### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by petereoin** [MscrmTools/MsCrmTools.UserSettingsUtility#35]
I am unable to install the plug-in
"An error occurred while copying files: The process cannot access the file
UserSettingsUtility.dll because it is being used by another process"

XRMToolBox v 1.2019.7.34

![XRMTOOLBOX - Error](https://user-images.githubusercontent.com/54530533/63678202-9c49d280-c7e6-11e9-9b28-9a8c6ec83efb.JPG)

**Comment by MscrmTools** [comment]
There is a known issue on XrmToolBox side for this particular plugin. I'm closing this issue since the root issue will be fixed in the next release of XrmToolBox
