### ISSUE TITLE
Track e-mail messages: New 5th option not available

### ISSUE THREAD

**Issue by clomsy** [MscrmTools/MsCrmTools.UserSettingsUtility#36]
The new option to have manual tracking on by selecting "No Email Messages" is not available within XRM User Settings Utility - any chance you can make this available?

![image](https://user-images.githubusercontent.com/39401584/66740128-a7c68b00-ee72-11e9-915e-7981b2fcb24e.png)

I've been waiting for Microsoft to release this feature forever and it would be really nice to set it globally in the organization

**Comment by MscrmTools** [comment]
On its way!
