### ISSUE TITLE
Add ability to set: Show emails not tracked in Dynamics 365 in the Activities list.

### ISSUE THREAD

**Issue by benjimmy** [MscrmTools/MsCrmTools.UserSettingsUtility#37]
Can we please add the ability to set this value?

Under emails:
Set record form options:
Show emails not tracked in Dynamics 365 in the Activities list. Yes / No

This defaults to yes and is confusing my users.

**Comment by MscrmTools** [comment]
This feature is on its way! thanks for asking

**Comment by MscrmTools** [comment]
Please note that this setting will be enable only if auto data capture feature is enabled for the organization/environment

**Comment by benjimmy** [comment]
Thank you!
