### ISSUE TITLE
Enhancement Request: Include Interactive Dashboards in Default Dashboard setting

### ISSUE THREAD

**Issue by benweston81** [MscrmTools/MsCrmTools.UserSettingsUtility#38]
The Default Dashboard setting only shows Classic Dashboards at present and does not contain Interactive Dashboards. I believe this would be as simple as changing the FetchXML query in the RetrieveDashboards method to include a type of 10. For example:

<pre><code>&lt;fetch&gt;
  &lt;entity name="systemform" &gt;
    &lt;attribute name="formid" /&gt;
    &lt;attribute name="name" /&gt;
    &lt;filter type="and" &gt;
      &lt;condition attribute="formactivationstate" operator="eq" value="1" /&gt;
      &lt;filter type="or" &gt;
        &lt;condition attribute="type" operator="eq" value="0" /&gt;
        &lt;condition attribute="type" operator="eq" value="10" /&gt;
      &lt;/filter&gt;
    &lt;/filter&gt;
    &lt;order attribute="name" /&gt;
  &lt;/entity&gt;
&lt;/fetch&gt;
</code></pre>

**Comment by MscrmTools** [comment]
Will add it
