### ISSUE TITLE
Default User Settings Not Applying for UCI

### ISSUE THREAD

**Issue by nic07crm** [MscrmTools/MsCrmTools.UserSettingsUtility#39]
Setting users Default Pane/Tab & Dashboard work appropriately for classic interface, however if the user switches to UCI (via an app) the defaults are not set the same.

**Comment by MscrmTools** [comment]
Thanks for reporting. 
Just need to check why and if there is specific fields for UCI

**Comment by nic07crm** [comment]
Hi - just checking to see if you have figured out how we can set defaults for UCI with the tool.

**Comment by nic07crm** [comment]
Hi there,

Just wanted to check in on this.

Thanks,

Nicole​

Williams
Concurrency, Inc.

**Comment by MscrmTools** [comment]
As far as I see, there is no new settings made for UCI, so I guess this is not possible.
I will try to get an answer from Microsoft

**Comment by esKaper** [comment]
Are there any new updates on this topic from Microsoft? As far as I have checked this setting with default pane is still not applying for UCI. Thank you in advance

**Comment by MscrmTools** [comment]
No news so far

**Comment by MscrmTools** [comment]
Ok, so as this setting is not exposed in UCI personnal settings. I guess it won't be honored at all
