### ISSUE TITLE
Enhancement Request: Make option "Show emails in conversation on Timeline" available

### ISSUE THREAD

**Issue by MasoudNazari** [MscrmTools/MsCrmTools.UserSettingsUtility#41]
Hi,

Is it possible to make the above mentioned option available?

Thanks for your efforts. 

Regards, Masoud

![Show emails in conversation on Timeline](https://user-images.githubusercontent.com/44478252/79316095-25438480-7f04-11ea-8d47-726cc689c724.png)

**Comment by MscrmTools** [comment]
I guess it should be possible.
Let me check the corresponding attribute and I will add it ASAP

**Comment by MscrmTools** [comment]
This looks like the appropriate attribute
![image](https://user-images.githubusercontent.com/10774317/79335923-2041fd80-7f23-11ea-954c-6741984f218b.png)

**Comment by MasoudNazari** [comment]
Hi,

Thanks for your message.

It seems tob e the right attribute.
Thank you and best regards,

Masoud Ranjbar Nazari
Senior Manager
[cid:image008.png@01D61331.516B9AA0]<https://www.orbis.de/>
ORBIS AG | Nell-Breuning-Allee 3-5 | 66115 Saarbrücken | Germany
Mobile: +49 151 53 67 99 93 | E-Mail: masoud.nazari@orbis.de<mailto:masoud.nazari@orbis.de>
www.orbis.de<http://www.orbis.de/>
[cid:image009.png@01D61331.516B9AA0]
Registered Seat: Saarbrücken
Commercial Register Court: Amtsgericht Saarbrücken, HRB 12022
Board of Management: Thomas Gard (Chairman), Michael Jung, Stefan Mailänder, Frank Schmelzer
Chairman of the Supervisory Board: Ulrich Holzer
[cid:image003.png@01D61331.5166B8A0]<https://www.facebook.com/ORBIS.AG>     [cid:image004.png@01D61331.5166B8A0] <https://www.linkedin.com/company/orbis-ag/>      [cid:image005.png@01D61331.5166B8A0] <https://www.xing.com/companies/orbisag>      [cid:image006.png@01D61331.5166B8A0] <https://twitter.com/ORBIS_AG>      [cid:image007.png@01D61331.5166B8A0] <https://vimeo.com/orbisag>

Von: MscrmTools <notifications@github.com>
Gesendet: Mittwoch, 15. April 2020 14:13
An: MscrmTools/MsCrmTools.UserSettingsUtility <MsCrmTools.UserSettingsUtility@noreply.github.com>
Cc: Nazari Masoud <Masoud.Nazari@orbis.de>; Author <author@noreply.github.com>
Betreff: Re: [MscrmTools/MsCrmTools.UserSettingsUtility] Enhancement Request: Make option "Show emails in conversation on Timeline" available (#41)


This looks like the appropriate attribute
[image]<https://user-images.githubusercontent.com/10774317/79335923-2041fd80-7f23-11ea-954c-6741984f218b.png>

**Comment by MscrmTools** [comment]
New release to be available soon

**Comment by MasoudNazari** [comment]
The new function works. That was incredibly fast! Thank you so much for your efforts!

**Comment by MscrmTools** [comment]
You’re welcome! Adding a new setting is not difficult. You are just lucky I had some time to do it today :)
