### ISSUE TITLE
Enhancement: Pin views as default personal views for entities

### ISSUE THREAD

**Issue by Niels-SL** [MscrmTools/MsCrmTools.UserSettingsUtility#42]
Would it be possible to pin views as the default personal views of users using the User Settings Utility? 

E.g. the default view for opportunities in our environment is 'My open opportunities'. However, for non-sales users, this view is empty since they do not own any opportunities.

To get around this, we use the [ModHeader Chrome extenstion](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) to impersonate the user, and change the default view on their behalf, so they get the best start using the system. 

It would be great to be able to do this in bulk using the User Settings Utility.

**Comment by MscrmTools** [comment]
This settings is not stored in usersettings table, so this tool is not the best for that purpose
