### ISSUE TITLE
What is the difference between No and No change ?

### ISSUE THREAD

**Issue by Relkotb** [MscrmTools/MsCrmTools.UserSettingsUtility#44]
I want to update Email Settings create contacts. 
But I am confused between No and No change. 
Would you advice what is the difference ?

**Comment by MscrmTools** [comment]
No change means the tool won't update the current setting. No change is not one of the value expected by Dataverse/Dynamics

**Comment by Relkotb** [comment]
So when I need not to create contacts, I should choose just **No** option.
Thank you so much :)
