### ISSUE TITLE
Plugins running on usersettings always run on behalf of the user instead of initiating user

### ISSUE THREAD

**Issue by hansgfixed** [MscrmTools/MsCrmTools.UserSettingsUtility#45]
Plugin context UserId and InitiatingUserId are the same when triggering a plugin on update of usersettings via the User Settings Utility Tool. Anyone aware of that behaviour? Is this by design?

`  executionContext.Tracer.Trace($"InitiatingUserId: {executionContext.Context.UserId}\nUserId: {executionContext.Context.InitiatingUserId}");`

> InitiatingUserId: e9b68232-3647-ea11-a813-000d3ab61b5c
> UserId: e9b68232-3647-ea11-a813-000d3ab61b5c

**Comment by MscrmTools** [comment]
usersettings are not updateable by anyone but the owner of the settings, so the user is impersonated. 
So it seems normal to me
