### ISSUE TITLE
User Settings Utility - Default Pane, Default Tab - not reporting correct options.

### ISSUE THREAD

**Issue by Tamim-53** [MscrmTools/MsCrmTools.UserSettingsUtility#53]
Hi - Default Pane, Default Tab are not reporting the option sets that are presented under Set Personal Options:

![image](https://github.com/user-attachments/assets/4f3d7b1f-9fa0-4fae-9438-ceb1b194d91d)
![image](https://github.com/user-attachments/assets/2cae4377-7569-484a-aa7f-afc91c1dec12)

Unless I'm doing something wrong, this very much looks like a bug.

---
- Deployment: Online
- DB Version: 9.2.24084.188
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.2024.7.27

**Comment by MscrmTools** [comment]
Hi, these items depend on the app selected in the toolbar.
Your screenshot shows panes and tabs for Outlook application whereas you are looking at Sales Hub application personal options

**Comment by Tamim-53** [comment]
Hiya - yes, thank you. You are right!
The reply was sincerely appreciated!
Tamim Sadikali.
    On Friday 20 September 2024 at 16:37:06 BST, MscrmTools ***@***.***> wrote:  
 
 


Hi, these items depend on the app selected in the toolbar.
Your screenshot shows panes and tabs for Outlook application whereas you are looking at Sales Hub application personal options
