### ISSUE TITLE
Enhancement: add possiblity to view and set format

### ISSUE THREAD

**Issue by daggen** [MscrmTools/MsCrmTools.UserSettingsUtility#8]
Hi,

I'm helping my clients with typical AM questions. As important data through CSV file is a common thing for one client and date formats is the normal problem it would be great if I could view the formats used by a specific user. Also be able to set them.

I'm referring to the formats that each user can find under Options -> Formats

Thanks

**Comment by GianiNoyez** [comment]
@daggen I'm looking for the same functionality.
